name: Release
on:
  push:
    branches:
      - master
      - alpha

jobs:
  # https://docs.github.com/en/actions/guides/publishing-nodejs-packages#publishing-packages-using-yarn
  # https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/github-actions.md
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: corepack enable

      - run: yarn install

      - run: yarn run build

      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
