name: Test
on: ["push", "pull_request"]

jobs:
  build:
    name: Test with coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: yarn test:coverage

    - name: Publish coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: './tests/coverage/lcov.info'
