name: Validate
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4

    - run: corepack enable

    - run: yarn install

    - run: yarn run test:coverage

    - uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4

    - run: corepack enable

    - run: yarn install

    - run: yarn run build

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4

    - run: corepack enable

    - run: yarn install

    - run: yarn run lint
